package com.Dropdown.test;

import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import com.Dropdown.logic.DropdownLogic;
import com.aventstack.extentreports.Status;

public class DropDownTest extends DropdownLogic {

	@Test
	public void test() {
		
	
		 logger=report.createTest("Test");
		
		logger.log(Status.INFO,"Initializing the Browser");
	invokeBrowser("chrome");
	
	logger.log(Status.INFO,"Opening the Website");
	openURL("https://mail.rediff.com/cgi-bin/login.cgi");
	
	logger.log(Status.INFO,"Click on Create new account link");
	createNewAccountLinkClick("/html/body/div/div[1]/div[1]/div[2]/form/div[2]/div/a/u");
	
	logger.log(Status.INFO,"Taking inputs from Excel File");
	Excel();
	
    logger.log(Status.INFO,"Checking available UserId and selecting from one of the autogenerated options");
    checkAvailability("//*[@id='tblcrtac']/tbody/tr[7]/td[3]/input[2]");
    autoSelectoption("//*[@id='radio_login']");
    
    logger.log(Status.INFO,"Selecting the Checkbox");
    selectCheckbox("//input[@type='checkbox']");
    
    logger.log(Status.INFO,"Selecting the date Dropdown");
    dayDropDown("//*[@id='tblcrtac']/tbody/tr[22]/td[3]/select[1]");
    monthDropDown("//*[@id='tblcrtac']/tbody/tr[22]/td[3]/select[2]");
    yearDropDown("//*[@id='tblcrtac']/tbody/tr[22]/td[3]/select[3]");
    
    logger.log(Status.INFO,"Selecting the country Dropdown and printing all countries list with total count and selecting and validating India");
    countryDropDown("//*[@id='country']");
    takeScreenShot();
   
    }
	
	@AfterTest
	public void endReport() {
		report.flush();
		driver.quit();
		
	}


}
